#!/bin/bash
echo "Welcome to the game."
echo "You will learn about Linux."
echo "This will be fun."
echo "No prior experience is needed."
echo "Are you ready to begin?"
echo "The first thing to know about Linux is how to change directories. A directory is a specific location where files are stored. Think of a folder holding paper documents. You can't look at a file if it is not in the folder that you are looking through. The cd command allows you to change directories. Type in 'cd part1' to continue."
